[[GAP_pkg_semigroups]]
arch = "aarch64"
git-tree-sha1 = "2ba5ee205d8f2a53fc9da097295a1c24b5a5fa85"
os = "macos"

    [[GAP_pkg_semigroups.download]]
    sha256 = "84ab227e36048ace5becdce1403ae32a8c39f8f4a5ca04c42034ad1ae114d56d"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_semigroups_jll.jl/releases/download/GAP_pkg_semigroups-v501.60300.0+0/GAP_pkg_semigroups.v501.60300.0.aarch64-apple-darwin.tar.gz"
[[GAP_pkg_semigroups]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "30df7126ba6334d32e72b8379d7212b5d19310bc"
libc = "glibc"
os = "linux"

    [[GAP_pkg_semigroups.download]]
    sha256 = "7982ace4c1f68b56632e826103b45bc61b72acd13fc34e9be8eff5d3fbbd12a3"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_semigroups_jll.jl/releases/download/GAP_pkg_semigroups-v501.60300.0+0/GAP_pkg_semigroups.v501.60300.0.aarch64-linux-gnu-cxx11.tar.gz"
[[GAP_pkg_semigroups]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "346797658b0083e222b70f4a571cfd36cceb2756"
libc = "musl"
os = "linux"

    [[GAP_pkg_semigroups.download]]
    sha256 = "47e885a49c162c4cf15863edc2a88d59ee5413057c1db09054c692ad0d592b89"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_semigroups_jll.jl/releases/download/GAP_pkg_semigroups-v501.60300.0+0/GAP_pkg_semigroups.v501.60300.0.aarch64-linux-musl-cxx11.tar.gz"
[[GAP_pkg_semigroups]]
arch = "aarch64"
git-tree-sha1 = "606689b66dc2c4e2d4397f2a887a96819f8b0d34"
os = "freebsd"

    [[GAP_pkg_semigroups.download]]
    sha256 = "d58695f08211e95f500d356948edf338aa04c055a3ee10e4d7cdfb83e6b0327b"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_semigroups_jll.jl/releases/download/GAP_pkg_semigroups-v501.60300.0+0/GAP_pkg_semigroups.v501.60300.0.aarch64-unknown-freebsd.tar.gz"
[[GAP_pkg_semigroups]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "34c7458dc9e6b1011444935afcf4d90995243873"
libc = "glibc"
os = "linux"

    [[GAP_pkg_semigroups.download]]
    sha256 = "c8f31a2b8e936f856459182c74246f243fab6d7936162c811414b619926dcd05"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_semigroups_jll.jl/releases/download/GAP_pkg_semigroups-v501.60300.0+0/GAP_pkg_semigroups.v501.60300.0.powerpc64le-linux-gnu-cxx11.tar.gz"
[[GAP_pkg_semigroups]]
arch = "riscv64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "867b5bd8cf268715a026bac983bda3f111f14512"
libc = "glibc"
os = "linux"

    [[GAP_pkg_semigroups.download]]
    sha256 = "6676863c501b019b5a882bc235a2e5d56546536c9c39e98e1c8e1a2556408ab8"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_semigroups_jll.jl/releases/download/GAP_pkg_semigroups-v501.60300.0+0/GAP_pkg_semigroups.v501.60300.0.riscv64-linux-gnu-cxx11.tar.gz"
[[GAP_pkg_semigroups]]
arch = "x86_64"
git-tree-sha1 = "06df2e9f50d9eae30b709d560a88ab255d1d892d"
os = "macos"

    [[GAP_pkg_semigroups.download]]
    sha256 = "855bd7a5d47dd8a70e1cd584fe98cde70fdd2c656613034c43ba20d83ff2710d"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_semigroups_jll.jl/releases/download/GAP_pkg_semigroups-v501.60300.0+0/GAP_pkg_semigroups.v501.60300.0.x86_64-apple-darwin.tar.gz"
[[GAP_pkg_semigroups]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "4db1ab8516490ad57f6d5bb0788c3ff3acaabaa1"
libc = "glibc"
os = "linux"

    [[GAP_pkg_semigroups.download]]
    sha256 = "817fa2afd7719fa9ce643acb07a2c5dd3590a5df310b9f205d97bd7f4c8707ee"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_semigroups_jll.jl/releases/download/GAP_pkg_semigroups-v501.60300.0+0/GAP_pkg_semigroups.v501.60300.0.x86_64-linux-gnu-cxx11.tar.gz"
[[GAP_pkg_semigroups]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "272eae24598f00a10cd15060be99ef97aee2c757"
libc = "musl"
os = "linux"

    [[GAP_pkg_semigroups.download]]
    sha256 = "e7a1b636f8a3fb9c14dcbdbbc17672aa35056d09d20263ac76d03a713fa69683"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_semigroups_jll.jl/releases/download/GAP_pkg_semigroups-v501.60300.0+0/GAP_pkg_semigroups.v501.60300.0.x86_64-linux-musl-cxx11.tar.gz"
[[GAP_pkg_semigroups]]
arch = "x86_64"
git-tree-sha1 = "a702046f6601fdbb506f8655187b10b41eefb3fb"
os = "freebsd"

    [[GAP_pkg_semigroups.download]]
    sha256 = "5e926de27e806192031181a135a47e2b4764853accb3dbcfbbf0765b9ab729be"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_semigroups_jll.jl/releases/download/GAP_pkg_semigroups-v501.60300.0+0/GAP_pkg_semigroups.v501.60300.0.x86_64-unknown-freebsd.tar.gz"
