[[GAP_pkg_semigroups]]
arch = "aarch64"
git-tree-sha1 = "5bebe1de4373745ca59daab75e8e19f25f2aacfc"
os = "macos"

    [[GAP_pkg_semigroups.download]]
    sha256 = "769ad71197260cc333aa290058e7b171409ca2e172a43b8124dac7dcad564125"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_semigroups_jll.jl/releases/download/GAP_pkg_semigroups-v501.50400.1+0/GAP_pkg_semigroups.v501.50400.1.aarch64-apple-darwin.tar.gz"
[[GAP_pkg_semigroups]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "9741aaf57bf10b816574f6c6765b0c7c73388de7"
libc = "glibc"
os = "linux"

    [[GAP_pkg_semigroups.download]]
    sha256 = "b6308c715f72273e6118205e0ddef2b66f033603c1670e0326b8a9b8eae0eaa9"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_semigroups_jll.jl/releases/download/GAP_pkg_semigroups-v501.50400.1+0/GAP_pkg_semigroups.v501.50400.1.aarch64-linux-gnu-cxx11.tar.gz"
[[GAP_pkg_semigroups]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "c585a794845405d401143ec88e556c3fa80b2d34"
libc = "musl"
os = "linux"

    [[GAP_pkg_semigroups.download]]
    sha256 = "27620a1abec1d351828bd43136d7fe2a40b2cdbceaad324f02a9b60887127104"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_semigroups_jll.jl/releases/download/GAP_pkg_semigroups-v501.50400.1+0/GAP_pkg_semigroups.v501.50400.1.aarch64-linux-musl-cxx11.tar.gz"
[[GAP_pkg_semigroups]]
arch = "aarch64"
git-tree-sha1 = "256108d1d52d911ce3554a30ed8b7b917d2ad603"
os = "freebsd"

    [[GAP_pkg_semigroups.download]]
    sha256 = "2dbf4e85e9f6bf5d608ae108a00c11dd2931e803e79fc67108fbcbe28e26ff9b"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_semigroups_jll.jl/releases/download/GAP_pkg_semigroups-v501.50400.1+0/GAP_pkg_semigroups.v501.50400.1.aarch64-unknown-freebsd.tar.gz"
[[GAP_pkg_semigroups]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "a7b469b3510a58c9748f6fe2f6afc9eae7e47191"
libc = "glibc"
os = "linux"

    [[GAP_pkg_semigroups.download]]
    sha256 = "e0f6f3fc97ee833d75311bb861874b95472b7adebb49f626c4142e12030e901e"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_semigroups_jll.jl/releases/download/GAP_pkg_semigroups-v501.50400.1+0/GAP_pkg_semigroups.v501.50400.1.powerpc64le-linux-gnu-cxx11.tar.gz"
[[GAP_pkg_semigroups]]
arch = "riscv64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "f5532f44ce3923b353dc0aff81eb21b21e50acaa"
libc = "glibc"
os = "linux"

    [[GAP_pkg_semigroups.download]]
    sha256 = "bbe4623a5a7d2e45d8f59139bd717f50e5718d2ab9cfc35c890f2aea4a849181"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_semigroups_jll.jl/releases/download/GAP_pkg_semigroups-v501.50400.1+0/GAP_pkg_semigroups.v501.50400.1.riscv64-linux-gnu-cxx11.tar.gz"
[[GAP_pkg_semigroups]]
arch = "x86_64"
git-tree-sha1 = "a8972641a3f0a78bf12888a81610e651f25f445c"
os = "macos"

    [[GAP_pkg_semigroups.download]]
    sha256 = "2b50c6b617ccb0078fb4b73d7ae6c0f4881c6bcb49d32327604c04063c23a19e"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_semigroups_jll.jl/releases/download/GAP_pkg_semigroups-v501.50400.1+0/GAP_pkg_semigroups.v501.50400.1.x86_64-apple-darwin.tar.gz"
[[GAP_pkg_semigroups]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "f7e7125b49e370f3d7a09beffa5b148c5d0db3e0"
libc = "glibc"
os = "linux"

    [[GAP_pkg_semigroups.download]]
    sha256 = "2470b9f58fc7394e1d4c1855eeee2fd7b1c61a4ef815841a821ffdd1af0ca3c7"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_semigroups_jll.jl/releases/download/GAP_pkg_semigroups-v501.50400.1+0/GAP_pkg_semigroups.v501.50400.1.x86_64-linux-gnu-cxx11.tar.gz"
[[GAP_pkg_semigroups]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "22b20e7dc12c13b24d8b9d753ea8fff5e7946353"
libc = "musl"
os = "linux"

    [[GAP_pkg_semigroups.download]]
    sha256 = "97f31ee4e1075e4fdabd7265fe950f97018fc62e59d9d10523b601560a7c2070"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_semigroups_jll.jl/releases/download/GAP_pkg_semigroups-v501.50400.1+0/GAP_pkg_semigroups.v501.50400.1.x86_64-linux-musl-cxx11.tar.gz"
[[GAP_pkg_semigroups]]
arch = "x86_64"
git-tree-sha1 = "22123bf428189c0492ee0834059397015bcaa39d"
os = "freebsd"

    [[GAP_pkg_semigroups.download]]
    sha256 = "0a660ebc1d0d93c01447b2218103cc13ba1e1de1efd45b1a4c94f3dea111c7e7"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_semigroups_jll.jl/releases/download/GAP_pkg_semigroups-v501.50400.1+0/GAP_pkg_semigroups.v501.50400.1.x86_64-unknown-freebsd.tar.gz"
